### ISSUE TITLE
 Enable responses automatically for all tests

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#34]
We can use pytest-responses to do this.

**Comment by Ishaan28malik** [comment]
I guess here we can directly use the responses utility library , link is in the description 
Responses are either registered or passed directly 

https://github.com/getsentry/responses

**Comment by marco-c** [comment]
We are already using responses, what we want is enabling it on all tests automatically. pytest-responses can be used for that.

**Comment by Ishaan28malik** [comment]
oh alright, yes that can be done

**Comment by Adrian-Tamas** [comment]
I assume that this would require something similar to what I have done in mozilla/code-review#49 so I would like to help here also however I did try to run the test locally and I get errors in the tests/test_phabricator.py tests because it does not find the files in the /tmp directory. It creates everything until the /repos/ folders but nothing past that
