### ISSUE TITLE
Remove release-services hooks

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage#73]
They are still triggered because of cron, we should stop triggering them completely (removing them is probably the best option).

**Comment by La0** [comment]
The production hook has been inactive for a day (i removed the cron schedule yesterday).
I removed **all** the other `codecoverage*` hooks produced by release services: the only remaining one is production bot.

The old backend on Heroku has been shutdown since yesterday morning after the DNS switch.

And we got new coverage data displayed in the frontend.

I think we can pull the plug:
1. remove old production hook
2. delete old production heroku instance

**Comment by La0** [comment]
@marco-c Should we proceed now ? 14 days without using that hook.

**Comment by marco-c** [comment]
Yeah, I think it's time!

**Comment by La0** [comment]
I made [a backup](https://paste.mozilla.org/Eakt28oA) of the release-services prod hook, just in case.
It's now deleted, same for heroku instance `shipit-production-codecoverage`.

We are now running 100% from that repo, on our own deployment.
